### ISSUE TITLE
Reasoning / Magical Merchant Question

### ISSUE THREAD

**Issue by Technology101** [Fluorohydride/ygopro#1481]
Hello guys,

I just had a quick question regarding the two cards: What does the GetSequence() method return? From what I can tell, the method takes in a single card and grabs the sequence. I have no clue what the sequence means. It is the position in the deck that specific card is contained? 

The reason I'm asking this: I want to create a modification to ygopro. I want external input to be available during gameplay. Specifically, I type in which card I drew (via a batch command writing to a file that a fstream will read) and compare it to the cards in the deck (via pop_back - ing every element into an array and searching for the correct data.code field) and placing all the cards from my array back into the card_vector, then drawing as per the source dictates.

I've managed to get the modification drawing correctly, and the only thing giving me trouble is these two cards! I don't know whether I should update the sequence everytime I mess with the deck, or something else entirely. If you could point me in the direction as to where I can control each excavated card before the ConfimDecktop method is called, I would be very appreciative. 

I've been working on this on and off for over a year now, and I do not plan to give up just yet,
Thank You for Your Time.

**Comment by salix5** [comment]
https://github.com/247321453/DataEditorX/blob/master/DataEditorX/data/_functions.txt
●int Card.GetSequence(Card c)
返回c在当前位置的序号
在场上时，序号代表所在的格子，从左往右分别是0-4，场地魔法格的序号为5，左右灵摆区域为6-7
在其它地方时，序号表示的是第几张卡，最下面的卡的序号为0

Basically it means:
return the sequence No. of c
MZONE: 0~4
SZONE: 0~4, 5=field magic, 6~7: pendulum zone
otherwise: location of the card, 0=bottom

I don't know if there is an English version.
