### ISSUE TITLE
BUG: When ritual summoning when 5 monster zone in use, you still can select monster in hand to release

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1669]
![image](https://cloud.githubusercontent.com/assets/13391795/12700122/d14ed932-c810-11e5-8d3a-ff644bfe1cd3.png)

And you can active ritual spell card when monster zone is full and no monster can be released.
![image](https://cloud.githubusercontent.com/assets/13391795/12700148/ea76a83a-c811-11e5-829b-d456947fc775.png)

**Comment by MobiusMei** [comment]
The ritual spell using in this process is '幻想的仪式',41426869,'イリュージョンの儀式',
with the code "Auxiliary.AddRitualProcGreater"
which allows the player to release monsters with total level greater than 1.
In this case, the spell should be able to release extra monsters from hand, or graveyard, as long as the the player also selects monster(s) from his/her side of filed.

The only "BUG" is the second condition, when all five monsters on your side of the field is not releasable.

The further concern would be ritual spells such as '异色眼降临',16494704,'オッドアイズ・アドベント', or  '影灵衣的万华镜',51124303,'影霊衣の万華鏡', which work differently as "release monster(s) up to the level of balabala" instead of "greater than the level of balabala". I haven't check these code yet, but they should be correct.

**Comment by MobiusMei** [comment]
The ritual spell using in this process is '幻想的仪式',41426869,'イリュージョンの儀式',
with the code "Auxiliary.AddRitualProcGreater"
which allows the player to release monsters with total level greater than 1.
In this case, the spell should be able to release extra monsters from hand, or graveyard, as long as the the player also selects monster(s) from his/her side of the field.

The only "BUG" is the second condition, when all five monsters on your side of the field is not releasable.

The further concern would be ritual spells such as '异色眼降临',16494704,'オッドアイズ・アドベント', or '影灵衣的万华镜',51124303,'影霊衣の万華鏡', which work differently as "release monster(s) up to the level of balabala" instead of "greater than the level of balabala". I haven't check these code yet, but they should be correct.
