### ISSUE TITLE
Request: Enable the surrender button in the 3rd or 1st turn.

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1689]
Now, the winner of a yugioh duel can often be decided in the first turn, so I think the surrender option should be enabled after each player had finished their first turn.

Besides, as the readme said, ygopro is a sample gui, so it shouldn't limit the surrender function.

请求在第3或第1回合显示投降按钮
现在游戏王决斗经常在第一回合就定了胜负，所以我觉得每个玩家都完成他们的第一个回合之后，就应该可以选择投降了。

此外，readme中说，ygopro是示例gui，所以它不应该限制投降功能。

**Comment by zh99998** [comment]
I prefer to keep current behavior.

**Comment by Zayelion** [comment]
@zh99998 any reasoning behind that choice?

**Comment by zh99998** [comment]
T4 is just 2 turn for opponent. 

for lose wait for 2 turn is not too painful.
for winner, after you have done many operation, any your opponent just don't play this game. it's ...depressed. 

that's why we are trying to block force exit. respect your opponent to play 2 turn.
if we let first turn surrender, it's no difference to force exit. but is legal and anyone can't say "don't do this". 

as other example, LOL/DOTA allow surrender after 20 minutes, not at beginning.

**Comment by Zayelion** [comment]
There are a number of issues surrounding a surrender that are handled poorly, to start with the user all to often press the [x] button to close the window, and trigger a degree of server faulting. The application makes no effort for if the user presses the [x] to notify the server/opponent that the user is closing it, they just drop the connection and depending on how the server is built there is some delay before the opponent is notified. 

If the user presses the close button the application should notify the opponent they are surrendering (similiar to how most word processors ask if you want to save a document that has unsaved changes), or set it as a separate win condition (rage quite, dis-honorable quit, connection error).

While we ourselves here have pride and mutal respect to others as duelist, others,... mostly children, do not share our views of honor respect and Yu-Jo Friendship. So we can not be idealistic in our implementations.

**Comment by TSoulgain** [comment]
well... another example...

if u just want to try a new idea and build a fun-deck or something which is not so powerful and .... and u join a game, then u'll find your opponent is using a powerful deck, such as EM or burning abyss or something else . It's also makes us depressed. Especially when u try to talk with the opponent “Hi guy, I just want to end this game quickly and admit defeated at the 5th turn”. while sometimes, ur opponent will say 'no' and keep on doing what they want to do even u just want to admit defeated, and u have to stay focus on it because if u lose your attention too long , u'll receive  punishment from the service.Well , isn't it unfair for these players too?

u just mentioned the LOL/Dota allow the surrender after 20 minutes, while u also need to realized that in Dota/LOL , u can see the opponent's choice and change your choice for an extra chance before game start while it's impossible In YGOpro for now. 

So can we add an extra choice which enable us to cancel the surrender limit in the settings when we want to start a new game? Thx.

**Comment by Loadedtothemax** [comment]
> if u just want to try a new idea and build a fun-deck or something which is not so powerful and .... and u join a game, then u'll find your opponent using a powerful deck, such as EM or burning abyss or something else . 

The reason we have these problems in the first place, is because we have access to all the cards at the start. In ygonline3 konami's sim, you didn't have access to all the cards. So their program had less of these problems. When you have to work for your cards you have less problems.

**Comment by Zayelion** [comment]
> One of the ways to solve this is for every sim to add support for duel messages like Percy.
Thats a shortcut to a larger issue of bad UI. It doesnt solve the issue itself, only band aids it and leads to problems requiring moderation.

**Comment by mercury233** [comment]
I think we can have more detailed setting for surrender.
For a match for score, player should can surrender at any time.
For a duel between friends, they may want to restart the duel at any time too.
For a duel with random player, we should make sure both player can have fun, so the surrender function should be enabled in a suitable time. I think the 3rd turn will be fine.

So we should let the server control the showing of surrender button, something like `MSG_ENABLE_SURRENDER`. And in the game client built-in server, just show the surrender button in the 1st turn.

-----------

I opened a vote in two of my group, and got:
![](https://cloud.githubusercontent.com/assets/13391795/13530998/16e1c0a0-e25f-11e5-9944-c2fc9fbe9e2c.gif)
![](https://cloud.githubusercontent.com/assets/13391795/13530999/171a8d54-e25f-11e5-87d3-f7d0aaa2fb6f.gif)
(Title: Do you support that we enable surrendering in 3rd turn?)
(1. No 2.Yes 3.I wish enable surrendering in 1st turn)

**Comment by mercury233** [comment]
So...

**Comment by Zayelion** [comment]
Implement
