### ISSUE TITLE
BUG: Some "destroyed by your opponent" effect will be able to activate when the card was equipped by Inzektor Exa-Beetle and Exa-Beetle is destroyed

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1750]
Most cards use `rp~=tp` to check "by your opponent", but in the situation as title, `rp` will be `PLAYER_NONE`.

Should we change all `rp~=tp` and `e:GetHandler():GetReasonPlayer()~=tp` to `rp==1-tp` ?

**Comment by salix5** [comment]
current destroy reasons:
REASON_BATTLE
REASON_EFFECT
REASON_COST(Koa'ki)
REASON_RULE

Reference:
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=17229&keyword=&tag=-1
When 2 unique monsters are on the field, 1 of them will be destroyed by REASON_RULE

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=18903&keyword=&tag=-1
Block Dragon can prevent all but REASON_RULE.

http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=17032&keyword=&tag=-1
If monsters with self-destroy are destroyed by battle, the self-destroyed effect will not apply.
Otherwise, it will apply in ダメージ計算後.

(Investigating)

**Comment by mercury233** [comment]
战斗和效果破坏都有reason player，但COST和规则破坏应该是没有的，装备怪兽破坏时装备卡破坏应属于规则破坏，这时`con(e,tp,eg,ep,ev,re,r,rp)`里的`rp`会是`PLAYER_NONE`，不等于`tp`。
但永遠の淑女之类部分卡判断“被对方破坏”使用的是`rp~=tp`，导致被甲虫装机艾可萨甲虫等卡装备后跟着破坏时也能发动效果。

**Comment by salix5** [comment]
考慮到規則破壞的話，用rp==1-tp判斷應該比較恰當
