### ISSUE TITLE
BUG: Shield & Sword don't work

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1787]
![image](https://cloud.githubusercontent.com/assets/13391795/16196260/f6184c6a-372f-11e6-9378-a61d4254c84c.png)

Btw, Performage Mirror Conductor will work

![image](https://cloud.githubusercontent.com/assets/13391795/16196389/4b1d9bc0-3730-11e6-9692-fb283f0cd5bf.png)

**Comment by destdev** [comment]
anything that switches original atk/def doesn't seem to work, Ojama Country also fails
also, I thought that somehow it might be connected with this
https://github.com/Fluorohydride/ygopro/issues/1778

since it was closed I thought it might have been fixed, but that problem is still present after our last update, did we miss anything?

**Comment by mercury233** [comment]
@destdev I think Qliphort was fixed after https://github.com/Fluorohydride/ygopro-core/commit/696ec1e7bd433d040f1388e604c6077511cc1a5e
