### ISSUE TITLE
BUG: Junk Collector can't copy the effect of Mystical Refpanel

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#1909]
![image](https://cloud.githubusercontent.com/assets/13391795/21646404/0612feb6-d2d1-11e6-81c3-25356a975319.png)
After activating _Junk Collector_, `c:CheckActivateEffect(false,true,false)` of _Mystical Refpanel_ will become nil, so it can't be copied.

**Comment by DailyShana** [comment]
This is because the effect of _Mystical Refpanel_ is activate at `EVENT_CHAINING`, see the special treatment in the script of _Traptrix Rafflesia_

**Comment by DailyShana** [comment]
When activating the effect of _Junk Collector_, there is a `break_effect()` before paying cost and excuting target (see https://github.com/Fluorohydride/ygopro-core/blob/973f3a6a83f4706b7abd9ce8763dc00caa7055b2/processor.cpp#L3938 and https://github.com/Fluorohydride/ygopro-core/blob/973f3a6a83f4706b7abd9ce8763dc00caa7055b2/processor.cpp#L4012), 
which makes the `EVENT_CHAINING` of the previous chain removed from `core.instant_event`, and `EVENT_CHAINING` is not in `core.point_event` either because it's not a point event.
That's why `c:CheckActivateEffect(false,true,false)` of `Mystical Refpanel` becomes nil at this timing.

At first sight it seems that these two calling of `break_effect()` can be removed, but not certain.
