### ISSUE TITLE
Work in progress funciton opinions

### ISSUE THREAD

**Issue by edo9300** [Fluorohydride/ygopro#1928]
I made a new type of function, Group.SelectUnselect(), this function could be very useful in almost all the summon/spsummon procedures, it allows you to put 2 groups as parameters, one from where you can select cards as usual, and the other.... from where you can unselect cards. 
https://youtu.be/SlqK2nBqx_s
this is a sample video, i used dark synchros because they require only 2 materials, but it could be used in other ways too.
Could this function be added into the core?

**Comment by Hello23-Ygopro** [comment]
I would like if that gets added too , i also remember a player could right-click to cancel attacks , but that was taken out of the source code a few versions ago , so it would be useful if that gets added back too with this

Also i think there should be the tip on the "Cancel" button that says "You can also right-click to [stop selecting materials]" or something , since not everyone will know you can right-click to cancel many things in Ygopro

**Comment by edo9300** [comment]
@Hello23-Ygopro this is another example with xyzs ;) https://youtu.be/U2Q4zaqrJ2g
But ATM these things are script based, and idk if I'll add the to the core, and for the cancelable, don't care about the texts in the buttons xD

**Comment by Hello23-Ygopro** [comment]
> this is another example with xyzs ;) https://youtu.be/U2Q4zaqrJ2g

Dont forget about Fusions , their important too

> But at the moment these things are script based, and i don't know if I'll add them to the core too (in the selectsynchromaterial and selectxyzmaterialfunctions)

Yeah i dont know if they will ever add it to the core , or anything about Dark Synchros since their not OCG/TCG , also alot of people might disagree and say that "since its an automated game, there should be less ways to take back your moves" , or something..
but if its something as small as selecting the wrong materials i think there should be an exception

> don't care about the texts in the buttons xD

Oh looks like your "Cancel" button is wrong in your video as "Enable sound effects"
https://github.com/Fluorohydride/ygopro/pull/1841/files
The texts are in the tooltips that show when you hover over that button
i think it was added for people that didnt know you can right-click to "stop selecting" stuff

Its definitely useful for a more user-friendly system , and there are still people that dont know about the monster tooltips, the hotkeys (F1~F4: Show the cards in your grave, banished zone, extra deck, xyz materials.) , stuff like that

**Comment by mercury233** [comment]
I think it should be fine if this feature is added

**Comment by edo9300** [comment]
@Hello23-Ygopro I'm working on fusions too, I'm rewriting the procedures used in ygopro Percy, I think that in a few days I'll upload this function and make the commit ;)

**Comment by Hello23-Ygopro** [comment]
Thank you ! I hope the right-click to cancel selecting an attack target gets added too

**Comment by edo9300** [comment]
@Hello23-Ygopro i committed these functinos in my repos: 
https://github.com/edo9300/ygopro-core/commit/54439d2e6ae27f5be3c649b58716a041f6378cc5

https://github.com/edo9300/ygopro/commit/8bc91334dab590ed2f0d2167f9bbd104c75859e8

now i don't have the time to make a pull request for this repository
