### ISSUE TITLE
Request: Make cards set by Duel.SSet hidden to opponent

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2106]
The opponent shouldn't know the accurate place of cards set by _Mirror Force Launcher_ or _Brandish Mechanism Multi-Roll_, but now since the cards comes from public area, the set cards are public to opponent.

**Comment by purerosefallen** [comment]
I think we have to update Duel.ShuffleSetCard. Since the client will remember where the card comes from, which will make the player know which is which. It would be fine if player can decide where the card should be set.
Another solution is to add a function Duel.ClearCardInfo to erase the card info from the client. But it gave player chance to modify the client to cheat. 
(So it's somehow necessary to make the server verify the client's MD5)
