### ISSUE TITLE
Create a organization `ygopro` to maintain the project

### ISSUE THREAD

**Issue by DongchengWang** [Fluorohydride/ygopro#2236]
Maintainance are becoming harder. I think a organization is needed for

1. organizing people
2. introducing new contributors
3. writing better docs
4. making iteration plans
...

**Comment by mercury233** [comment]
emmm 至少参与一点点开发再来指点江山？

**Comment by purerosefallen** [comment]
I don't think having an organization is needed because..

1. YGOPro is maintained by people from all over the world. We are not being leaded by any individuals.
2. As for maintainers in China. We have [MyCard](https://mycard.moe) which has most of the YGOPro maintainers. If you wish, you may join us. Contact 星光pokeboy (pokeboyexn@gmail.com) for further information.
