### ISSUE TITLE
BUG: Gnomaterial can activate if Grinder Golem is summoned when the field is empty

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2237]
![image](https://user-images.githubusercontent.com/13391795/67612027-9dd94c00-f7d1-11e9-85ec-705344265666.png)
I guess it is because my field is empty when the tokens are summoned.

**Comment by edo9300** [comment]
The issue here is that the tokens and golem aren't summoned at the same time, like the card says, in the summon op, they're summoned with step and then the summon is finalized at the end of the target, then golem is summoned, thus making 2 separated summons, and gnomaterial is triggered by the tokens being summoned, even if a correct handling would also put golem in the summoned group

**Comment by edo9300** [comment]
Update (i should have done this before), this interaction is correct, as as it's stated in the official db "The special summoning of “Torch Token” and the special summoning of “Torch Golem” are not handled at the same time.", so gnome can trigger because when the tokens are summoned, your field is currently empty, so its conditions are satisfied, and since that's a mandatory effect, it will trigger regardless of what happen afterwards

**Comment by mallu11** [comment]
What about the "topologic" Monster?The condition of event spsummon success is unlike the gnomaterial.When the monster spsummon success in the linked zone,if the Link Monsters move to other zones or other sequences to make the spsummon monsters aren't in the linked zone after all effects resolve,the "topologic" Monster can't activate its effect.

**Comment by DailyShana** [comment]
move `Duel.GetFieldGroupCount(tp,LOCATION_ONFIELD,0)==0` to the cost or target check
