### ISSUE TITLE
BUG: Comic Hand may execute operation with wrong params

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro#2339]
@salix5 
If any player has _Astrograph Sorcerer_ in deck, and _Comic Hand_ lost _Toon World_ before it is equipped, `c33453260.activate` will be executed with the params of `c76794549.checkop`, vice versa.
Replay:
[2021-04-05 21-56-24.zip](https://github.com/Fluorohydride/ygopro/files/6258495/2021-04-05.21-56-24.zip)

In this replay, if we add
```lua
if eg then Debug.Message(eg:GetFirst():GetCode()) end
```
to `c33453260.activate`, we can see that the missing `eg` of `c76794549.checkop` appeared here.

**Comment by mercury233** [comment]
@salix5 I think this is related to `EFFECT_FLAG_CONTINUOUS_TARGET`

**Comment by salix5** [comment]
confirming

**Comment by pyrQ** [comment]
Seems to be related to the following issue.

Puzzle instructions:
- Activate "Void Launch" during the Standby Phase and choose to use its effect.
- "Void Launch" correctly sends itself to the GY (because you control a non-"Infernoid" monster) and its effect is not applied.
- However, "eg" for the EVENT_TO_GRAVE effect of "Skull Invitation" is nil so its operation that should deal 300 damage to the player errors out (after finding this issue and debuging we realised that the operation of "Void Launch" is using the "eg" that should be used by "Skull Invitation").

```lua
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI,5)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)

--Main Deck (yours)
Debug.AddCard(58446973,0,0,LOCATION_DECK,0,POS_FACEDOWN)

--Monster Zones (yours)
Debug.AddCard(1929294,0,0,LOCATION_MZONE,2,POS_FACEUP_ATTACK,true)

--Spell & Trap Zones (yours)
Debug.AddCard(98139712,0,0,LOCATION_SZONE,1,POS_FACEUP)
Debug.AddCard(94432298,0,0,LOCATION_SZONE,2,POS_FACEDOWN)

Debug.ReloadFieldEnd()```Sidenote, this seems to be more of a core problem, so shouldn't this issue be in the core repo and not in the client one.
