### ISSUE TITLE
"Duck Dummy" not protecting monsters immune to it on its field

### ISSUE THREAD

**Issue by Lyris12** [Fluorohydride/ygopro#2355]
![image](https://user-images.githubusercontent.com/10141610/123097664-5835b200-d3fe-11eb-9233-469cbc9099e7.png)
"Duck Dummy" has its effects, but it does not seem to protect monsters on its user's field which are immune to its effect... Shouldn't the Ultimate Falcon be unselectable as an attack target, in a case like this?

**Comment by mercury233** [comment]
Please report issues at the main repo unless you are sure which part of code in the core or script have problem.

**Comment by salix5** [comment]
https://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=2&cid=13249&request_locale=ja
 Question
自身の『①：このカードは、このカードのアドバンス召喚のためにリリースしたカードと元々の種類（モンスター・魔法・罠）が同じカードの効果を受けない』モンスター効果によって、モンスターと魔法カードの効果を受けない状態の「真竜剣皇マスターP」が自分のモンスターゾーンに表側表示で存在しています。

この状況で、相手のモンスターゾーンに「ダックドロッパー」が表側表示で存在し、『●このカードがモンスターゾーンに存在する限り、相手モンスターの攻撃は全て直接攻撃になる』モンスター効果が適用されている場合、自分は「真竜剣皇マスターP」でどのように攻撃を行う事ができますか？

Answer
質問の状況の場合、「真竜剣皇マスターP」はモンスターの効果を受けませんので、相手の「ダックドロッパー」のモンスター効果が適用されている場合でも、その攻撃は直接攻撃にはならず、通常通りモンスターを対象として攻撃宣言を行う事になります。 

A: Duck Dummy (in Gemini form)
B: Master Peace, the True Dracoslaying King (unaffected by monster effects)
Master Peace is unaffected by Duck Dummy, and it can attack any target.

**Comment by Lyris12** [comment]
But Duck dummy can attack master peace, which shouldn't be the case, should it?

**Comment by shadowfox87** [comment]
There are two effects of Duck Dummy, one affects the monster and the other affects the player. 

1. The attacks from your opponent's monsters become direct attacks. (This affects the monster. Therefore, monsters like Master Peace which are unaffected, don't attack directly).
2. Neither player can target this card with card effects. (This affects the player so even if a monster is unaffected, it cannot target duck dummy with card effects.)

Lastly, Player 1 controls a Master Peace that is unaffected by Duck Dummy and Duck Dummy on their side of the field. Player 2 *also* controls a second Duck Dummy. If Player 2 declares an attack with the second Duck Dummy, it should be a direct attack since it is affected by Player 1's Duck Dummy.

However, currently, in ygopro, Player 2 can select Player 1's Master Peace as an attack target.
