### ISSUE TITLE
卡片是如何被绘制的?

### ISSUE THREAD

**Issue by Reisen1969** [Fluorohydride/ygopro#2419]
我把原本倾斜的视角设成平整了
![image](https://user-images.githubusercontent.com/76834109/155180005-01eac8b8-cde6-4e0d-b4b0-7063086db007.png)
然后想要把点击区域 `hovered_location` 也弄平整,

图省事直接把转换的步骤去掉了,直接用上了"鼠标移动的实时坐标"
```
	double screenx = x / 1024.0 * 1.35 - 0.90;
		double screeny = y / 640.0 * 0.84 - 0.42;
		double angle = 0.798056 - atan(screeny);	//0.798056 = arctan(8.0/7.8)
		double vlen = sqrt(1.0 + screeny * screeny);
		//double boardx = 4.2 + 7.8 * screenx / vlen / cos(angle);
		//double boardy = 8.0 - 7.8 * tan(angle);
                double boardx = x
               double boardy = y
```
然后首先改了卡组的坐标,改成了合适的数值
```
SetS3DVertex(vFieldDeck[0], 873, 510, 932, 596, 0, 1, 0, 0, 0, 0);
```

![image](https://user-images.githubusercontent.com/76834109/155181019-7441fccd-391f-49ba-b7b4-72d25a1175b6.png)

结果就是 :可以在正确的范围内点击了,但是卡组的图像却没有了

后来发现 鼠标移动的实时坐标 的 数量级  跟 `materials.cpp` 文件里的坐标不一样, 很困惑

**Comment by edo9300** [comment]
If you are interested, i too have a working topdown implementation for edopro, that still needs some polishing before it's ready to be released 
![image](https://user-images.githubusercontent.com/18705342/155212501-757a0e48-e812-4419-8375-2fb608587dff.png)
(it can be found in the topdown branch in my repo https://github.com/edo9300/edopro/tree/topdown). You might want to avoid wasting time redoing the same things over again. In my case though it was easier to implement because of the previous refactors i did in the drawing code, feel free to give a look.

**Comment by Reisen1969** [comment]
> If you are interested, i too have a working topdown implementation for edopro, that still needs some polishing before it's ready to be released 
> ![image](https://user-images.githubusercontent.com/18705342/155212501-757a0e48-e812-4419-8375-2fb608587dff.png)
> (it can be found in the topdown branch in my repo https://github.com/edo9300/edopro/tree/topdown). You might want to avoid wasting time redoing the same things over again. In my case though it was easier to implement because of the previous refactors i did in the drawing code, feel free to give a look.

thanks for suggestion

**Comment by mercury233** [comment]
_我个人是不想在irrlicht这个引擎上花太多时间的，所以没有去深究_

**Comment by purerosefallen** [comment]
@edo9300 Just a bit curious, how to make the position of atk / def text look good

**Comment by edo9300** [comment]
> @edo9300 Just a bit curious, how to make the position of atk / def text look good

Long ago i rewrote part of the drawing code that made that handled automatically without any change.

**Comment by yybbwc** [comment]
为什么要把倾斜的视角变成平整？
